### ISSUE TITLE
Improper patch creation when changing an array to an object

### ISSUE THREAD

**Issue by jflitton** [cujojs/jiff#29]
First off, thanks for this wonderful library!  I've written an event store which uses it and I've encountered the following behavior which I believe to be a bug:

```
var a = {
  "stuff": ['x']
};

var b = {
  "stuff": {
    "a": "x"
  }
};

var patch = jiff.diff(a,b);
```

results in a patch like this:
```
[
  {
    "op": "add"
    "path": "/stuff/a"
    "value": "x"
  }
  {
    "op": "test"
    "path": "/stuff/0"
    "value": "x"
  }
  {
    "op": "remove"
    "path": "/stuff/0"
  }
]
```

This patch cannot be applied however because the path "/stuff/a" isn't valid for an array:
```
c = jiff.patch(patch, a);  // SyntaxError: invalid array index a
```

The patch I expected to see is:
```
[
  {
    "op": "replace"
    "path": "/stuff"
    "value": {
      "a": "x"
    }
  }
]
```

Am I way off base here?

**Comment by briancavalier** [comment]
@jflitton Thanks for the detailed report.  That sure seems like a bug!  I should have time to look into it this weekend.  I bet the problem is that our [`isValidObject` check is too lax](https://github.com/cujojs/jiff/blob/master/lib/jsonPatch.js#L62-L64) and causes [this code branch](https://github.com/cujojs/jiff/blob/master/jiff.js#L80-L82) to allow an `Array` and an object.  Should be super-easy to fix.

**Comment by briancavalier** [comment]
Yep, that was it.  Could you try the [fix-issue-29 branch](https://github.com/cujojs/jiff/tree/fix-issue-29) to see if it works for you?  Thanks!

**Comment by jflitton** [comment]
@briancavalier that did the trick!  Thanks for the quick fix.

**Comment by briancavalier** [comment]
Cool, thanks for confirming.  [Version 0.7.2 just landed](https://github.com/cujojs/jiff/releases/tag/0.7.2) with this fix :confetti_ball:
